### ISSUE TITLE
About Button not fitting on frame

### ISSUE THREAD

**Issue by dylngg** [Wh3at1y/SwitchSetupGUI#5]
I don't know how to fix it, but the about button is out of frame(plus we need to actually do something with it) We should either change the frame size or decrease the button size. Plus, personally I think the font size should be smaller (like 14)

**Comment by Wellrabbit** [comment]
Yeah downsize the font and then maybe if you make the screen size bigger until it comes back on screen it usually works. Then drag it to a more manageable place.
